/**
 * Generate docs/openapi.json + src/generated/openapi.json (served at /openapi.json) from the zod contract (zod 4
 * toJSONSchema). The Verdict component is the public contract (PublicVerdict, src/api/public-names.ts): the document
 * never names the model or its vendor (tests/public-names.test.ts).
 *   npx tsx scripts/openapi.ts          write both files
 *   npx tsx scripts/openapi.ts --check  write nothing; exit 1 when either committed file differs from the contract
 *                                       (deploy gate and CI: a route or schema change ships with its document)
 */
import { z } from "zod";
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { MarketRegistration, StrictV0Verdict } from "../src/resolve/schema";
import { PublicVerdict } from "../src/api/public-names";
import { WEBHOOK_EVENTS } from "../src/webhooks/deliver";
import { EARLY_REVEAL_LABEL } from "../src/shadow/follows";
import { CHALLENGE_TTL_MINUTES, SIGNATURE, WALLET_ADDRESS } from "../src/billing/wallet";
import { EXPORT_COLUMNS, EXPORT_PLATFORMS, EXPORT_ROW_CAP } from "../src/shadow/export";
import { EVALUATION_KEY_DAYS, EVALUATION_WATCH_LIMIT, FREE_EVALUATION_CREDITS } from "../src/api/keys";
import { AUTO_KEY_DAILY_CAP_DEFAULT, AUTO_KEYS_PER_NETWORK_PER_DAY } from "../src/api/evaluation-key";
import { CARD_PACKS, PACK_IDS, WHOP_SIGNATURE_TOLERANCE_S } from "../src/billing/whop";
import { PRINT_PRICE_CREDITS } from "../src/api/prints";
import { OFFICIAL_SERIES } from "../src/resolve/official";
import { CHECKOUT_ROUTE, CONTACT_PATH, PAY_BY_CARD_PATH, USDC_NOT_OFFERED } from "../src/billing/top-up";
import { Platform } from "../src/resolve/schema";
import { REVEAL_EVENT_CAP_CREDITS, REVEAL_INCLUDED_PLANS, REVEAL_LATE_MINUTES, REVEAL_PRICE_CREDITS, REVEAL_REASONS } from "../src/shadow/reveal";
import { followCap, PLANS } from "../src/shadow/follows";

const schemas = {
  MarketRegistration: z.toJSONSchema(MarketRegistration, { unrepresentable: "any" }),
  Verdict: z.toJSONSchema(PublicVerdict, { unrepresentable: "any" }),
  StrictV0Verdict: z.toJSONSchema(StrictV0Verdict, { unrepresentable: "any" }),
  InlineEvidence: { type: "object", properties: { source_kind: { type: "string", enum: ["tenant_supplied", "github_api", "base_log", "solana_log", "web_fetch"], default: "tenant_supplied" }, source_url: { type: "string" }, text: { type: "string", maxLength: 200000 }, structured: {}, observed_at: { type: "string", format: "date-time" } } },
  SuccessEnvelope: { type: "object", required: ["ok", "data", "request_id", "schema_version"], properties: { ok: { const: true }, data: {}, request_id: { type: "string" }, schema_version: { type: "string" } } },
  RevealAccess: { type: "object", description: `What a private early reveal cost and why it was released or locked (src/shadow/reveal.ts): a RESOLVED verdict costs ${REVEAL_PRICE_CREDITS} credits on the free and pay-as-you-go plans, once per tenant and market, at most ${REVEAL_EVENT_CAP_CREDITS} per event; included in ${REVEAL_INCLUDED_PLANS.join(", ")}; free when not RESOLVED`, required: ["reason", "credits_charged", "replayed"], properties: { reason: { type: "string", enum: [...REVEAL_REASONS] }, credits_charged: { type: "integer", minimum: 0 }, replayed: { type: "boolean" } } },
  LockedReveal: { type: "object", description: "A RESOLVED verdict the tenant has not received: insufficient_credits (the price of the leg, the balance and where to top up; nothing was charged, the next read after a top-up releases and charges it), billing_unavailable (billing could not be reached; nothing was charged) or account_unavailable", required: ["reason", "price_credits", "balance", "top_up", "read", "message"], properties: { reason: { type: "string", enum: ["insufficient_credits", "billing_unavailable", "account_unavailable"] }, price_credits: { type: "integer" }, balance: { type: ["integer", "null"] }, top_up: { description: "The card rail while card checkout is offered, else support; never a USDC address. null unless insufficient_credits", type: ["object", "null"] }, read: { type: "string" }, message: { type: "string" } } },
  ErrorEnvelope: { type: "object", required: ["ok", "error", "request_id", "schema_version"], properties: { ok: { const: false }, error: { type: "object", required: ["code", "message"], properties: { code: { type: "string" }, message: { type: "string" } } }, request_id: { type: "string" }, schema_version: { type: "string" }, remaining: { type: "integer" }, resets_at: { type: "string" }, retry_after_seconds: { type: "integer" }, how_to_proceed: { type: "string" } } },
};
const sec = [{ bearerAuth: [] }, { apiKeyAuth: [] }];
const r = (desc: string, schema: unknown = { $ref: "#/components/schemas/SuccessEnvelope" }) => ({ description: desc, content: { "application/json": { schema } } });
const E = { $ref: "#/components/schemas/ErrorEnvelope" };
const packs = PACK_IDS.map((p) => `"${p}": $${CARD_PACKS[p].priceCents / 100} for ${CARD_PACKS[p].credits.toLocaleString("en-US")} credits`).join(", ");
const html = (desc: string) => ({ description: desc, content: { "text/html": { schema: { type: "string" } } } });
const topUp = `top_up: {method: "card", checkout: "${CHECKOUT_ROUTE}", page: "<site>${PAY_BY_CARD_PATH}", packs[] {pack, price, currency, credits}} while card checkout is offered, else {method: "contact_support", page: "<site>${CONTACT_PATH}"}; never a USDC address`;
/** The path parameter of the follow and early-reveal routes: a uuid or a venue id (src/shadow/follows.ts parseMarketRef). */
const marketRef = (name: string) => ({ name, in: "path", required: true, description: `The market's uuid, or its venue id <platform>:<external_id> (platform ${Platform.options.join(", ")}) exactly as /record and the home page print it. A venue id names only a public shadow market (not a tenant's, not a test market, not deleted); none or more than one match answers 404`, schema: { type: "string" } });
const doc = {
  openapi: "3.1.0",
  info: { title: "Resolve API", version: "1.0.0-beta", description: "Automated resolution infrastructure for long-tail prediction markets. Verdicts are contract-validated; UNRESOLVED always carries a caveat; a non-observation is never a negative verdict. Percentages in the track record appear only after 100 reconciled events per platform (the legs of one multi-outcome event count once)." },
  servers: [{ url: "https://resolve.rafaemush.workers.dev" }],
  components: { securitySchemes: { bearerAuth: { type: "http", scheme: "bearer" }, apiKeyAuth: { type: "apiKey", in: "header", name: "X-Api-Key" } }, schemas },
  paths: {
    "/v1/resolve": { post: { summary: "Resolve a market from stored or inline evidence (bill-then-run; Idempotency-Key supported)", security: sec, parameters: [{ name: "Idempotency-Key", in: "header", schema: { type: "string" } }], requestBody: { content: { "application/json": { schema: { type: "object", properties: { market_id: { type: "string", format: "uuid" }, market: { $ref: "#/components/schemas/MarketRegistration" }, evidence: { $ref: "#/components/schemas/InlineEvidence" }, fetch: { type: "boolean", default: false } } } } } }, responses: { 200: r("Verdict (or StrictV0Verdict for strict_v0 tenants) plus request_id, credits_charged, credits_refunded, balance, route (precheck | structured | web_evidence)", { allOf: [{ $ref: "#/components/schemas/SuccessEnvelope" }, { properties: { data: { $ref: "#/components/schemas/Verdict" } } }] }), 202: r("Idempotent replay of a request still in flight"), 400: r("validation_error", E), 401: r("auth_required | invalid_key | key_expired", E), 402: r(`insufficient_credits (price_credits, balance, route and ${topUp}, at top level; the message says the same)`, E), 409: r("conflict: fetch:true while a poll of the market's watch is in progress (a scheduled dispatch or another fetch holds it); nothing ran, retry in a minute", E), 422: r("strict_v0 tenants: UNSAFE_INPUT with no verdict body", E), 429: r("rate_limited | daily_cap_reached with remaining, resets_at, retry_after_seconds, how_to_proceed", E), 503: r("UPSTREAM_UNAVAILABLE: billing or model unavailable, or the watch lease for fetch:true could not be taken (no credits charged), or error_reason VERDICT_NOT_RECORDED: the verdict could not be stored, the charge is refunded (credits_refunded) and a replay of that Idempotency-Key answers the same; retry with a new key", E) } } },
    "/v1/markets": { post: { summary: "Register a market and its watches in one transaction. Sources must match their kind (GitHub: repos/{owner}/{repo}/pulls/{n}, issues/{n}, releases, releases/tags/{tag}, events, or the repository itself for a numeric_threshold resolver; base_log: base:0x + 40 hex; solana_log: solana:<account>), name the resolver's own repo, PR, contract or account, and web sources must be public https URLs on the default port; web_render is not accepted yet. At registration: robots.txt (a disallow = unsupported_source; a robots.txt that answers 5xx or 429, or not at all, could not be checked: 503), contract code on Base, and a Solana account that exists and is not a program. Re-registering the same external_id returns the existing market", security: sec, requestBody: { content: { "application/json": { schema: { $ref: "#/components/schemas/MarketRegistration" } } } }, responses: { 201: r("market_id, status (open | unsupported_source), reasons, watches"), 400: r("validation_error: schema, source policy or a Solana program id", E), 403: r("validation_error: watch limit reached (watch_limit, active_watches, requested_watches at top level)", E), 409: r("conflict: the service's Base watch capacity is reached (max_base_watches, active_base_watches, requested_base_watches at top level)", E), 503: r("UPSTREAM_UNAVAILABLE: a registration check could not be made (Base or Solana RPC, robots.txt); nothing was stored, retry after Retry-After", E) } }, get: { summary: "List markets", security: sec, responses: { 200: r("markets[]") } } },
    "/v1/markets/{id}": { get: { summary: "Market with watches", security: sec, responses: { 200: r("market, watches"), 404: r("not_found", E) } }, delete: { summary: "Soft-delete a market and deactivate its watches", security: sec, responses: { 200: r("deleted") } } },
    "/v1/markets/{id}/resolutions": { get: { summary: "Resolution history for a market", security: sec, responses: { 200: r("resolutions[] (id, resolution_status, winning_outcome, confidence_score, error_code, error_reason, caveats, determination_basis, engine_version, thresholds_version, credits_charged, credits_refunded, created_at)") } } },
    "/v1/markets/{id}/follow": {
      post: { summary: `Follow a public shadow market (open, not a test market) for the private early reveal: its committed verdicts at GET /v1/shadow/{market_id} and as shadow.committed / shadow.revealed webhooks, labeled "${EARLY_REVEAL_LABEL}". Idempotent. With the body {"scope":"event"} every open public leg of the market's event is followed in one transaction (an official release's legs on every venue, a Polymarket event's legs), all or nothing against the follow limit; without a body, or with {"scope":"market"}, the one market. Follows of open markets per tenant (read from the tenant's plan): ${PLANS.map((p) => `${p} ${followCap(p) ?? "unlimited"}`).join(", ")}; a follow of a settled market does not count. A free-plan (evaluation) follow delivers only while the tenant holds a live key. A RESOLVED reveal costs ${REVEAL_PRICE_CREDITS} credits on the free and payg plans, once per market, at most ${REVEAL_EVENT_CAP_CREDITS} per event (reveal_price states this account's terms)`, security: sec, parameters: [marketRef("id")], requestBody: { required: false, content: { "application/json": { schema: { type: "object", additionalProperties: false, properties: { scope: { type: "string", enum: ["market", "event"], default: "market" } } } } } }, responses: { 201: r("scope market: follow_id, market_id (the uuid), market (platform:external_id), following, already_following=false, follows_counted (follows of open markets, what the limit counts), follow_limit (null = unlimited), events, read, endpoints_subscribed (active endpoints that receive shadow.committed), reveal_price {terms (pays | included_plan | grandfathered), credits_per_resolved_leg, event_cap_credits, note}, note, warning (only when endpoints_subscribed is 0). scope event (at least one leg followed): scope, event_key, market_id, market, following, legs (open public legs of the event), followed (followed now), already_following, follows_counted, follow_limit, events, read (/v1/shadow/export), endpoints_subscribed, reveal_price, note, warning"), 200: r("already following (scope market: already_following=true; scope event: followed=0): the same fields"), 400: r("validation_error: an id that is neither a uuid nor a venue id, a body that is not {scope: market | event}, the tenant's own market, or a market no longer open", E), 403: r("validation_error: follow limit reached (follow_limit, follows_counted at top level; scope event also legs, already_following and event_key, and nothing was followed)", E), 404: r("not_found: no such public shadow market (or a venue id that matches more than one)", E), 503: r("UPSTREAM_UNAVAILABLE: no follow was recorded", E) } },
      delete: { summary: "Stop following (soft delete); following again later creates a new follow", security: sec, parameters: [marketRef("id")], responses: { 200: r("unfollowed (the market's uuid)"), 400: r("validation_error: neither a uuid nor a venue id", E), 404: r("not_found: not following this market, or no public shadow market with that venue id", E), 503: r("UPSTREAM_UNAVAILABLE", E) } },
    },
    "/v1/follows": { get: { summary: "Active follows, newest first (at most 1000; active_follows is the full count), with follows_counted (follows of open markets, what the limit counts) and the plan's follow_limit. When follows_counted exceeds the limit (after a plan change), only the oldest follows up to the limit receive early reveals and a warning says so", security: sec, responses: { 200: r("follows[] (follow_id, market_id, followed_at, market platform:external_id, status, deadline_utc), active_follows, follows_counted, follow_limit, truncated, warning (only when follows_counted > follow_limit)"), 503: r("UPSTREAM_UNAVAILABLE", E) } } },
    "/v1/shadow/export": { get: { summary: `Export the followed markets this account is entitled to (the same rule as GET /v1/shadow/{market_id}: the plan's follow limit, and a live key on the free plan), one row per market, labeled "${EARLY_REVEAL_LABEL}": the latest commitment_sha256, committed_at, committed_status and committed_outcome, the evidence hashes, the number of commits, and once the platform resolves the market, official_outcome, official_at, official_at_source (gamma_closed_time is the platform's timestamp; limitless_api_poll and first_observed_poll are the first poll that saw the outcome, so lead_seconds is an upper bound), agreement and lead_seconds. A RESOLVED latest verdict is priced like every reveal (${REVEAL_PRICE_CREDITS} credits on free and payg, once per market, at most ${REVEAL_EVENT_CAP_CREDITS} per event, never refunded for a read): a row this account has not received is exported locked, with committed_status and committed_outcome empty; the reveal column says why each row is shown or locked (RevealAccess.reason, not_resolved, or empty without a commit). Never the nonce or the preimage. The oldest ${EXPORT_ROW_CAP} follows are read (truncated says when there are more). format=csv answers RFC 4180 CSV with a header row (Content-Type text/csv; X-Resolve-Truncated, X-Resolve-Credits-Charged, X-Resolve-Locked); the default is the JSON envelope. Never 402: locked rows answer 200 with top_up`, security: sec, parameters: [
      { name: "platform", in: "query", schema: { type: "string", enum: [...EXPORT_PLATFORMS] } },
      { name: "since", in: "query", description: "A UTC day (YYYY-MM-DD) or an ISO 8601 time: rows whose latest commit or final reconciliation was recorded at or after it", schema: { type: "string" } },
      { name: "format", in: "query", schema: { type: "string", enum: ["json", "csv"], default: "json" } },
    ], responses: { 200: { description: `JSON: rows[] (${EXPORT_COLUMNS.join(", ")}), count, columns, truncated, filters, credits_charged, locked_rows (rows exported locked), balance, top_up and locked_note (only when a row is locked for insufficient_credits), label, note, disclaimer; or the same rows as CSV`, content: { "application/json": { schema: { $ref: "#/components/schemas/SuccessEnvelope" } }, "text/csv": { schema: { type: "string" } } } }, 400: r("validation_error: platform, since or format", E), 503: r("UPSTREAM_UNAVAILABLE: the follows or the report view could not be read (never an empty export)", E) } } },
    "/v1/shadow/{market_id}": { get: { summary: `Private early reveal of a followed market ("${EARLY_REVEAL_LABEL}"): every committed verdict, newest first, with its commitment_sha256, committed_at, posted state and evidence hashes. Never the nonce or the preimage: those appear only in the public reveal. When a commit is RESOLVED the read is priced: ${REVEAL_PRICE_CREDITS} credits on the free and payg plans, once per tenant and market (every commit of it, every later read: free), at most ${REVEAL_EVENT_CAP_CREDITS} per event, never refunded for a read; included in ${REVEAL_INCLUDED_PLANS.join(", ")}; a commit that is not RESOLVED is always shown. At a short balance every RESOLVED commit is answered locked (verdict null, locked true) with the locked object, 200 and never 402; the read after a top-up releases and charges it. 404 unless the tenant follows the market; 403 when the follow is above the plan's follow limit (after a plan change) or a free-plan tenant holds no live key`, security: sec, parameters: [marketRef("market_id")], responses: { 200: r("market_id, platform, external_id, market, status, deadline_utc, label, reveal (RevealAccess, null when no commit is RESOLVED), locked (LockedReveal or null), latest, commits[] (commitment_sha256, committed_at, posted, posted_at, verdict {resolution_status, winning_outcome, confidence_score, caveats, determination_basis, thresholds_version} or null for a pre-v2 commit or a locked one, locked (true when this RESOLVED commit is withheld), evidence {raw_sha256, canonical_sha256}), credits_charged (this read), balance (null when the read was not priced), how_to_verify, disclaimer"), 400: r("validation_error", E), 403: r("validation_error: the follow is above the plan's follow limit, or the evaluation has ended", E), 404: r("not_found: not following this market", E), 503: r("UPSTREAM_UNAVAILABLE", E) } } },
    "/v1/prints": { get: { summary: `Every official series Resolve records first prints for (${Object.keys(OFFICIAL_SERIES).length} series): series, label, unit (what value is), period_format, latest {period, observed_at, read} (the latest period recorded; null before the first) and next_release {period, release_at, read} (the soonest scheduled release; null when none is scheduled). Free: 0 credits`, security: sec, responses: { 200: r("series[] {series, label, unit, period_format, latest, next_release}, count, credits_charged (0), price_credits {list, print}, read"), 401: r("auth_required | invalid_key | key_expired", E), 429: r("rate_limited | daily_cap_reached", E), 503: r("UPSTREAM_UNAVAILABLE: the first-print store could not be read", E) } } },
    "/v1/prints/{series}/{period}": { get: { summary: `The first print of one official release, as Resolve recorded it the first time it read the publisher's release (never revised): value (see unit in GET /v1/prints), value_text (as published), deciding_text (the text it was read from), observed_at (when Resolve first read it), release_at (the scheduled release; null when not in the calendar), source_url, raw_sha256 (the SHA-256 of the upstream response body Resolve read), corroboration.status (agree | disagree | unavailable | inconclusive | single_source; null when none was recorded) and verify. ${PRINT_PRICE_CREDITS} credit per served print, charged once per request: a replay of the same Idempotency-Key for the same print is free (replayed=true, X-Idempotent-Replay: true). Before the release, or while Resolve has not recorded it yet (up to 6 h after the release; 72 h for an election count): status scheduled with release_at, 0 credits. Free keys may call it`, security: sec, parameters: [
      { name: "series", in: "path", required: true, schema: { type: "string", enum: Object.keys(OFFICIAL_SERIES) } },
      { name: "period", in: "path", required: true, description: "The series' period_format (GET /v1/prints): YYYY-MM for a monthly print, YYYY-Qn for a quarterly one, YYYY-MM-DD for a decision or election day", schema: { type: "string", pattern: "^\\d{4}-(\\d{2}(-\\d{2})?|Q[1-4])$" } },
      { name: "Idempotency-Key", in: "header", schema: { type: "string" } },
    ], responses: { 200: r("status recorded: series, period, value, value_text, deciding_text, observed_at, release_at, source_url, raw_sha256, corroboration {status} or null, verify, credits_charged (1, or 0 on a replay), balance, replayed; or status scheduled: series, period, release_at, note, credits_charged (0), balance"), 401: r("auth_required | invalid_key | key_expired", E), 402: r("insufficient_credits (balance, price_credits and top_up at top level: the card rail while card checkout is offered, else support; never a USDC address): nothing charged, nothing served", E), 404: r("not_found: an unknown series, a period not in the series' format, no first print recorded and none scheduled, or a stored observation made before its scheduled release (not a first print); nothing charged", E), 405: r("method_not_allowed: HEAD is refused (Allow: GET) before anything is read or charged: an answer to HEAD carries no print", E), 429: r("rate_limited | daily_cap_reached", E), 503: r("UPSTREAM_UNAVAILABLE: the first-print store or billing could not be reached; nothing charged, nothing served", E) } } },
    "/v1/resolutions/{id}": { get: { summary: "One resolution by request_id", security: sec, responses: { 200: r("verdict"), 404: r("not_found", E) } } },
    "/v1/account": { get: { summary: "Tenant, plan, credits, the registered sender wallet (wallet_address), when the last credits.low notice went out (low_credit_notified_at, cleared by any purchase or grant), key usage", security: sec, responses: { 200: r("tenant, key") } } },
    "/v1/account/wallet/challenge": { get: { summary: `Issue a single-use wallet registration challenge (valid ${CHALLENGE_TTL_MINUTES} minutes) for a wallet this account controls. The message to sign is exactly "Resolve wallet registration\ntenant: <tenant_id>\naddress: <lowercase address>\nnonce: <nonce>\nissued: <ISO time>"`, security: sec, parameters: [{ name: "address", in: "query", required: true, schema: { type: "string", pattern: WALLET_ADDRESS.source } }], responses: { 200: r("challenge_id, address (lowercase), message, nonce, issued_at, expires_at, sign, submit"), 400: r("validation_error: address missing or not 0x + 40 hex", E), 503: r("UPSTREAM_UNAVAILABLE: no challenge was issued", E) } } },
    "/v1/account/wallet": { post: { summary: "Register the wallet that signed a challenge (EIP-191 personal_sign of the challenge message; externally owned accounts only); it replaces a previously registered wallet. USDC deposits are not offered unless GET /v1/payments/address answers", security: sec, requestBody: { content: { "application/json": { schema: { type: "object", required: ["challenge_id", "signature"], additionalProperties: false, properties: { challenge_id: { type: "string", format: "uuid" }, signature: { type: "string", pattern: SIGNATURE.source } } } } } }, responses: { 200: r("wallet_address, previous_wallet_address, registered=true"), 400: r("validation_error: malformed body, or error_reason bad_signature (the signature does not recover to the challenge's address)", E), 404: r("not_found: no such challenge for this account", E), 409: r("validation_error with error_reason challenge_used (single use) or wallet_taken (registered to another account)", E), 410: r("validation_error with error_reason challenge_expired", E), 503: r("UPSTREAM_UNAVAILABLE: nothing was registered", E) } } },
    "/v1/usage": { get: { summary: "Credits by reason and resolutions by route over a window", security: sec, parameters: [{ name: "days", in: "query", schema: { type: "integer", default: 30 } }], responses: { 200: r("window_days, credits_by_reason, resolutions_by_route (keys <route>/<resolution_status>, route precheck | structured | web_evidence), recent_ledger") } } },
    "/v1/payments/address": { get: { summary: `Only while USDC deposits are offered (off unless the service switches them on): USDC (Base) receiving address, the PAYG tiers the deposit is credited at (a deposit gets the rate of the highest tier its amount reaches: floor(amount x credits_per_usdc)), the packs they buy, the registered sender wallet, confirmation policy (safe tag). Deposits emit payment.credited. While they are not offered it answers 503 "${USDC_NOT_OFFERED}" with error_reason USDC_NOT_OFFERED and the card pointer`, security: sec, responses: { 200: r("chain, token, token_contract, receiving_address, registered_sender_wallet, credits_per_usdc (base rate), payg_tiers[] {min_usdc, credits_per_usdc}, packs[] {usdc, credits, credits_per_usdc}, confirmation_policy, register_wallet"), 503: r(`${USDC_NOT_OFFERED} (error_reason USDC_NOT_OFFERED, ${topUp}), deposits not enabled, or pricing unavailable`, E) } } },
    "/v1/keys/rotate": { post: { summary: "Mint a new key; the calling key expires in 24 h, or at its own expiry if that is sooner. Rotation never extends a key: the new key keeps the calling key's expiry (an evaluation key stays inside its 30 days)", security: sec, responses: { 201: r("key (shown once), key_id, expires_at (null = never), note") } } },
    "/v1/webhooks": { post: { summary: `Register an https endpoint (secret shown once). events: a subset of ${WEBHOOK_EVENTS.join(", ")} (default: all). The first delivery attempt is made as the event happens (a few per event, early reveals the tenant paid for first; the rest by the 5-minute queue drain, in the same order); failed attempts retry on a backoff of 60 s, 5 min, 30 min, 2 h, 12 h, 24 h, then dead-letter. shadow.committed carries reveal (RevealAccess) and locked (LockedReveal or null): a locked one has verdict null and a venue object that proposes nothing. A paid shadow.committed that none of the tenant's endpoints received within ${REVEAL_LATE_MINUTES} minutes of committed_at is refunded once`, security: sec, requestBody: { content: { "application/json": { schema: { type: "object", required: ["url"], properties: { url: { type: "string", format: "uri", pattern: "^https://" }, events: { type: "array", items: { type: "string", enum: [...WEBHOOK_EVENTS] } } } } } } }, responses: { 201: r("endpoint + secret"), 400: r("validation_error", E) } }, get: { summary: "List endpoints", security: sec, responses: { 200: r("endpoints[]") } } },
    "/v1/webhooks/{id}": { delete: { summary: "Deactivate an endpoint", security: sec, responses: { 200: r("deleted") } } },
    "/v1/webhooks/deliveries": { get: { summary: "Delivery log (pending | delivering | delivered | dlq)", security: sec, responses: { 200: r("deliveries[]") } } },
    "/v1/webhooks/deliveries/{id}/replay": { post: { summary: "Replay a delivered or dead-lettered event", security: sec, responses: { 200: r("replayed") } } },
    "/v1/track-record": { get: { summary: "Public track record rendered from v_track_record (60 s cache; test markets excluded; one agreement per market; the legs of one multi-outcome event are one event: n_events_* columns, event_precision; cumulative percentages with 95 % Wilson intervals only after 100 reconciled events per platform)", responses: { 200: r("rows[] per platform and week; before 100 reconciled events each percentage column holds the gate text"), 503: r("UPSTREAM_UNAVAILABLE", E) } } },
    "/v1/track-record/verify": { get: { summary: "Look up a commitment (public, no auth). Before the reveal: market, committed_at, posted, revealed=false (never the nonce). After the reveal: preimage, nonce, committed verdict, official outcome, agreement; sha256(preimage) = commitment_sha256", parameters: [{ name: "hash", in: "query", required: true, schema: { type: "string", pattern: "^[0-9a-fA-F]{64}$" } }], responses: { 200: r("commitment_sha256, market (platform:external_id), committed_at, posted, posted_at, message_id (the legs of one event share their commit message), revealed [+ preimage_version, preimage, nonce, committed, official, agreement, reveal_posted once revealed]"), 400: r("validation_error", E), 404: r("not_found", E), 503: r("UPSTREAM_UNAVAILABLE", E) } } },
    "/v1/billing/checkout": { post: { summary: `Open a card checkout (Whop, the merchant of record) for a credit pack for this key's account: ${packs}. Whop receives this account's id, never the key. The credits are added when Whop confirms the payment (usually within a minute; GET /v1/account shows the balance); a free test key's account moves to pay as you go and its key stops expiring. Credits are a non-refundable prepayment for API services and do not expire while the account is open; a card refund or chargeback removes them. Never cached`, security: sec, requestBody: { content: { "application/json": { schema: { type: "object", required: ["pack"], properties: { pack: { type: "string", enum: [...PACK_IDS] } } } } } }, responses: { 200: r("checkout_url (Whop's hosted checkout), checkout_id, pack, price, currency, credits, merchant_of_record, note"), 400: r("validation_error: pack is not one of the packs", E), 401: r("auth_required | invalid_key | key_expired", E), 429: r("rate_limited | daily_cap_reached", E), 503: r("UPSTREAM_UNAVAILABLE: card checkout not yet available, not configured, or Whop did not open the checkout; nothing was charged", E) } } },
    "/billing/checkout": { post: { summary: "The pricing page's card form (public HTML; no-store): the key and the pack in the form body, answered with a 303 to the Whop checkout opened for that key's account (the key is never passed on, echoed or kept). Refusals answer an HTML page with the reason", requestBody: { content: { "application/x-www-form-urlencoded": { schema: { type: "object", required: ["key", "pack"], properties: { key: { type: "string" }, pack: { type: "string", enum: [...PACK_IDS] } } } } } }, responses: { 303: { description: "Location: the Whop checkout" }, 400: html("the form was not complete"), 401: html("the key was not accepted"), 429: html("too many requests for this key"), 503: html("card checkout not yet available, or the checkout could not be opened; nothing was charged") } } },
    "/billing/done": { get: { summary: "Where Whop sends the buyer after paying (public HTML). It reads nothing: credits come only from Whop's signed confirmation", responses: { 200: html("text/html") } } },
    "/webhooks/whop": { post: { summary: `Whop's signed payment, refund and dispute events (Standard Webhooks: webhook-id, webhook-timestamp within ${WHOP_SIGNATURE_TOLERANCE_S} s, webhook-signature v1 HMAC-SHA256 of the raw body). Called by Whop only; an unverified request answers 401 and nothing is stored`, responses: { 200: r("received, type, result"), 401: r("invalid_signature", E), 409: r("conflict: another event of the same payment is being processed; Whop retries", E), 413: r("validation_error: body too large", E), 503: r("UPSTREAM_UNAVAILABLE: not configured or the database is unavailable; Whop retries", E) } } },
    "/v1/request-key": { post: { summary: `Request a test key (public, no auth). Issues an evaluation key on the spot and returns it once (data.key): rsl_test_, ${FREE_EVALUATION_CREDITS} credits, valid ${EVALUATION_KEY_DAYS} days, structured verdicts only, up to ${EVALUATION_WATCH_LIMIT} watches. One key per email address every ${EVALUATION_KEY_DAYS} days, ${AUTO_KEYS_PER_NETWORK_PER_DAY} keys a day per network (IPv4 address or IPv6 /64) and a daily cap on keys issued this way (${AUTO_KEY_DAILY_CAP_DEFAULT} by default); past any of these, or when the service is unsure, no key is issued (key_issued=false) and a person answers by email. At most 5 requests per hour per IP address`, requestBody: { content: { "application/json": { schema: { type: "object", required: ["name", "email", "company", "purpose"], properties: { name: { type: "string", maxLength: 100, description: "No links" }, email: { type: "string", format: "email", maxLength: 254 }, company: { type: "string", maxLength: 200, description: "Company or project (alias: project)" }, purpose: { type: "string", maxLength: 1000 }, venue: { type: "string", maxLength: 100 } } } }, "application/x-www-form-urlencoded": { schema: { type: "object" } } } }, responses: { 200: r(`received=true, key_issued, note; when key_issued: key (shown once, never stored), key_id, environment, plan, credits, watch_limit, expires_at, docs, next and pay_by_card (<site>${PAY_BY_CARD_PATH}, while card checkout is offered) (JSON); for a form post, an HTML page with the key or a confirmation. Never cached`), 400: r("validation_error", E), 429: r("rate_limited", E), 503: r("UPSTREAM_UNAVAILABLE: nothing was stored", E) } } },
    "/health": { get: { summary: "Liveness + one database read", responses: { 200: r("service, schema_version, thresholds_version, engine_version (opaque engine label), web_evidence_routes_enabled, migrations_applied, git_sha") } } },
    "/bot": { get: { summary: "What ResolveBot fetches and why, how it stays polite (declared user agent, robots.txt for web pages, per-page spacing, conditional requests) and how to opt out (robots.txt for web pages; an issue for official releases and public APIs) (public HTML, no auth)", responses: { 200: { description: "text/html", content: { "text/html": { schema: { type: "string" } } } } } } },
  },
};
const args = process.argv.slice(2);
if (args.some((a) => a !== "--check")) { console.error("usage: npx tsx scripts/openapi.ts [--check]"); process.exit(2); }
const OUTPUTS = ["src/generated/openapi.json", "docs/openapi.json"];
const json = JSON.stringify(doc, null, 2) + "\n";
const summary = `${Object.keys(doc.paths).length} paths, ${Object.keys(schemas).length} schemas`;
if (args.includes("--check")) {
  const stale = OUTPUTS.filter((p) => !existsSync(p) || readFileSync(p, "utf8") !== json);
  for (const p of stale) console.log(`DRIFT ${p}`);
  if (stale.length) { console.log(`${stale.length} file(s) differ from the contract (${summary}): run npx tsx scripts/openapi.ts and commit`); process.exit(1); }
  console.log(`openapi.json up to date: ${summary}`);
} else {
  mkdirSync("src/generated", { recursive: true });
  mkdirSync("docs", { recursive: true });
  for (const p of OUTPUTS) writeFileSync(p, json);
  console.log(`openapi.json: ${summary}`);
}
