/** Generate docs/openapi.json + src/generated/openapi.json from the zod contract (zod 4 toJSONSchema). */
import { z } from "zod";
import { writeFileSync, mkdirSync } from "node:fs";
import { MarketRegistration, Verdict, StrictV0Verdict } from "../src/resolve/schema";
import { WEBHOOK_EVENTS } from "../src/webhooks/deliver";
import { EARLY_REVEAL_LABEL } from "../src/shadow/follows";

const schemas = {
  MarketRegistration: z.toJSONSchema(MarketRegistration, { unrepresentable: "any" }),
  Verdict: z.toJSONSchema(Verdict, { unrepresentable: "any" }),
  StrictV0Verdict: z.toJSONSchema(StrictV0Verdict, { unrepresentable: "any" }),
  InlineEvidence: { type: "object", properties: { source_kind: { type: "string", enum: ["tenant_supplied", "github_api", "base_log", "solana_log", "web_fetch"], default: "tenant_supplied" }, source_url: { type: "string" }, text: { type: "string", maxLength: 200000 }, structured: {}, observed_at: { type: "string", format: "date-time" } } },
  SuccessEnvelope: { type: "object", required: ["ok", "data", "request_id", "schema_version"], properties: { ok: { const: true }, data: {}, request_id: { type: "string" }, schema_version: { type: "string" } } },
  ErrorEnvelope: { type: "object", required: ["ok", "error", "request_id", "schema_version"], properties: { ok: { const: false }, error: { type: "object", required: ["code", "message"], properties: { code: { type: "string" }, message: { type: "string" } } }, request_id: { type: "string" }, schema_version: { type: "string" }, remaining: { type: "integer" }, resets_at: { type: "string" }, retry_after_seconds: { type: "integer" }, how_to_proceed: { type: "string" } } },
};
const sec = [{ bearerAuth: [] }, { apiKeyAuth: [] }];
const r = (desc: string, schema: unknown = { $ref: "#/components/schemas/SuccessEnvelope" }) => ({ description: desc, content: { "application/json": { schema } } });
const E = { $ref: "#/components/schemas/ErrorEnvelope" };
const doc = {
  openapi: "3.1.0",
  info: { title: "Resolve API", version: "1.0.0-beta", description: "Automated resolution infrastructure for long-tail prediction markets. Verdicts are contract-validated; UNRESOLVED always carries a caveat; a non-observation is never a negative verdict. Percentages in the track record appear only after 100 reconciled markets per platform." },
  servers: [{ url: "https://resolve.rafaemush.workers.dev" }],
  components: { securitySchemes: { bearerAuth: { type: "http", scheme: "bearer" }, apiKeyAuth: { type: "apiKey", in: "header", name: "X-Api-Key" } }, schemas },
  paths: {
    "/v1/resolve": { post: { summary: "Resolve a market from stored or inline evidence (bill-then-run; Idempotency-Key supported)", security: sec, parameters: [{ name: "Idempotency-Key", in: "header", schema: { type: "string" } }], requestBody: { content: { "application/json": { schema: { type: "object", properties: { market_id: { type: "string", format: "uuid" }, market: { $ref: "#/components/schemas/MarketRegistration" }, evidence: { $ref: "#/components/schemas/InlineEvidence" }, fetch: { type: "boolean", default: false } } } } } }, responses: { 200: r("Verdict (or StrictV0Verdict for strict_v0 tenants) plus request_id, credits_charged, credits_refunded, balance, route", { allOf: [{ $ref: "#/components/schemas/SuccessEnvelope" }, { properties: { data: { $ref: "#/components/schemas/Verdict" } } }] }), 202: r("Idempotent replay of a request still in flight"), 400: r("validation_error", E), 401: r("auth_required | invalid_key | key_expired", E), 402: r("insufficient_credits (price_credits, balance, route at top level)", E), 422: r("strict_v0 tenants: UNSAFE_INPUT with no verdict body", E), 429: r("rate_limited | daily_cap_reached with remaining, resets_at, retry_after_seconds, how_to_proceed", E), 503: r("UPSTREAM_UNAVAILABLE: billing or model unavailable (no credits charged), or error_reason VERDICT_NOT_RECORDED: the verdict could not be stored, the charge is refunded (credits_refunded) and a replay of that Idempotency-Key answers the same; retry with a new key", E) } } },
    "/v1/markets": { post: { summary: "Register a market and its watches (robots and contract checks at registration)", security: sec, requestBody: { content: { "application/json": { schema: { $ref: "#/components/schemas/MarketRegistration" } } } }, responses: { 201: r("market_id, status (open | unsupported_source), reasons, watches"), 400: r("validation_error", E), 403: r("watch limit reached", E) } }, get: { summary: "List markets", security: sec, responses: { 200: r("markets[]") } } },
    "/v1/markets/{id}": { get: { summary: "Market with watches", security: sec, responses: { 200: r("market, watches"), 404: r("not_found", E) } }, delete: { summary: "Soft-delete a market and deactivate its watches", security: sec, responses: { 200: r("deleted") } } },
    "/v1/markets/{id}/resolutions": { get: { summary: "Resolution history for a market", security: sec, responses: { 200: r("resolutions[]") } } },
    "/v1/markets/{id}/follow": {
      post: { summary: `Follow a public shadow market (open, not a test market) for the private early reveal: its committed verdicts at GET /v1/shadow/{market_id} and as shadow.committed / shadow.revealed webhooks, labeled "${EARLY_REVEAL_LABEL}". Idempotent. Follows of open markets per tenant: 50, Growth 500, Platform unlimited (read from the tenant's plan); a follow of a settled market does not count. A free-plan (evaluation) follow delivers only while the tenant holds a live key`, security: sec, parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { 201: r("follow_id, market_id, following, already_following=false, follows_counted (follows of open markets, what the limit counts), follow_limit (null = unlimited), events, read, endpoints_subscribed (active endpoints that receive shadow.committed), warning (only when endpoints_subscribed is 0)"), 200: r("already following: the same fields with already_following=true"), 400: r("validation_error: bad id, the tenant's own market, or a market no longer open", E), 403: r("validation_error: follow limit reached (follow_limit, follows_counted at top level)", E), 404: r("not_found: no such public shadow market", E), 503: r("UPSTREAM_UNAVAILABLE: no follow was recorded", E) } },
      delete: { summary: "Stop following (soft delete); following again later creates a new follow", security: sec, parameters: [{ name: "id", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { 200: r("unfollowed"), 400: r("validation_error", E), 404: r("not_found: not following this market", E), 503: r("UPSTREAM_UNAVAILABLE", E) } },
    },
    "/v1/follows": { get: { summary: "Active follows, newest first (at most 1000; active_follows is the full count), with follows_counted (follows of open markets, what the limit counts) and the plan's follow_limit. When follows_counted exceeds the limit (after a plan change), only the oldest follows up to the limit receive early reveals and a warning says so", security: sec, responses: { 200: r("follows[] (follow_id, market_id, followed_at, market platform:external_id, status, deadline_utc), active_follows, follows_counted, follow_limit, truncated, warning (only when follows_counted > follow_limit)"), 503: r("UPSTREAM_UNAVAILABLE", E) } } },
    "/v1/shadow/{market_id}": { get: { summary: `Private early reveal of a followed market ("${EARLY_REVEAL_LABEL}"): every committed verdict, newest first, with its commitment_sha256, committed_at, posted state and evidence hashes. Never the nonce or the preimage: those appear only in the public reveal. 404 unless the tenant follows the market; 403 when the follow is above the plan's follow limit (after a plan change) or a free-plan tenant holds no live key`, security: sec, parameters: [{ name: "market_id", in: "path", required: true, schema: { type: "string", format: "uuid" } }], responses: { 200: r("market_id, platform, external_id, market, status, deadline_utc, label, latest, commits[] (commitment_sha256, committed_at, posted, posted_at, verdict {resolution_status, winning_outcome, confidence_score, caveats, determination_basis, thresholds_version} or null for a pre-v2 commit, evidence {raw_sha256, canonical_sha256}), how_to_verify, disclaimer"), 400: r("validation_error", E), 403: r("validation_error: the follow is above the plan's follow limit, or the evaluation has ended", E), 404: r("not_found: not following this market", E), 503: r("UPSTREAM_UNAVAILABLE", E) } } },
    "/v1/resolutions/{id}": { get: { summary: "One resolution by request_id", security: sec, responses: { 200: r("verdict"), 404: r("not_found", E) } } },
    "/v1/account": { get: { summary: "Tenant, plan, credits, key usage", security: sec, responses: { 200: r("tenant, key") } } },
    "/v1/usage": { get: { summary: "Credits by reason and resolutions by route over a window", security: sec, parameters: [{ name: "days", in: "query", schema: { type: "integer", default: 30 } }], responses: { 200: r("usage") } } },
    "/v1/payments/address": { get: { summary: "USDC (Base) receiving address, credits per USDC, confirmation policy (safe tag)", security: sec, responses: { 200: r("payment instructions"), 503: r("deposits not enabled", E) } } },
    "/v1/keys/rotate": { post: { summary: "Mint a new key; the calling key expires in 24 h, or at its own expiry if that is sooner. Rotation never extends a key: the new key keeps the calling key's expiry (an evaluation key stays inside its 30 days)", security: sec, responses: { 201: r("key (shown once), key_id, expires_at (null = never), note") } } },
    "/v1/webhooks": { post: { summary: `Register an https endpoint (secret shown once). events: a subset of ${WEBHOOK_EVENTS.join(", ")} (default: all). The first delivery attempt is made as the event happens (a few per event; the rest by the 5-minute queue drain); failed attempts retry on a backoff of 60 s, 5 min, 30 min, 2 h, 12 h, 24 h, then dead-letter`, security: sec, requestBody: { content: { "application/json": { schema: { type: "object", required: ["url"], properties: { url: { type: "string", format: "uri", pattern: "^https://" }, events: { type: "array", items: { type: "string", enum: [...WEBHOOK_EVENTS] } } } } } } }, responses: { 201: r("endpoint + secret"), 400: r("validation_error", E) } }, get: { summary: "List endpoints", security: sec, responses: { 200: r("endpoints[]") } } },
    "/v1/webhooks/{id}": { delete: { summary: "Deactivate an endpoint", security: sec, responses: { 200: r("deleted") } } },
    "/v1/webhooks/deliveries": { get: { summary: "Delivery log (pending | delivering | delivered | dlq)", security: sec, responses: { 200: r("deliveries[]") } } },
    "/v1/webhooks/deliveries/{id}/replay": { post: { summary: "Replay a delivered or dead-lettered event", security: sec, responses: { 200: r("replayed") } } },
    "/v1/track-record": { get: { summary: "Public track record rendered from v_track_record (60 s cache; test markets excluded; one agreement per market; cumulative percentages with a 95 % Wilson interval only after 100 reconciled markets per platform)", responses: { 200: r("rows[] per platform and week"), 503: r("UPSTREAM_UNAVAILABLE", E) } } },
    "/v1/track-record/verify": { get: { summary: "Look up a commitment (public, no auth). Before the reveal: market, committed_at, posted, revealed=false (never the nonce). After the reveal: preimage, nonce, committed verdict, official outcome, agreement; sha256(preimage) = commitment_sha256", parameters: [{ name: "hash", in: "query", required: true, schema: { type: "string", pattern: "^[0-9a-fA-F]{64}$" } }], responses: { 200: r("commitment_sha256, market (platform:external_id), committed_at, posted, posted_at, message_id, revealed [+ preimage_version, preimage, nonce, committed, official, agreement, reveal_posted once revealed]"), 400: r("validation_error", E), 404: r("not_found", E), 503: r("UPSTREAM_UNAVAILABLE", E) } } },
    "/health": { get: { summary: "Liveness + one database read", responses: { 200: r("service status") } } },
  },
};
mkdirSync("src/generated", { recursive: true });
mkdirSync("docs", { recursive: true });
const json = JSON.stringify(doc, null, 2) + "\n";
writeFileSync("src/generated/openapi.json", json);
writeFileSync("docs/openapi.json", json);
console.log("openapi.json:", Object.keys(doc.paths).length, "paths,", Object.keys(schemas).length, "schemas");
